name: Replace appID
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "appId: 'JlXUGO3ZcoTO3pK2BSb38cc2', //Production: 'LH8ZzpbwJuHH6xGFk6GgmtSC'; Development: 'JlXUGO3ZcoTO3pK2BSb38cc2'"
          replace: "appId: 'LH8ZzpbwJuHH6xGFk6GgmtSC',"
          include: "**App.vue" 
