name: Replace Strings

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace strings in src/App.vue
      run: |
        sed -i "s/appId: 'JlXUGO3ZcoTO3pK2BSb38cc2', \/\/Production: 'LH8ZzpbwJuHH6xGFk6GgmtSC'; Development: 'JlXUGO3ZcoTO3pK2BSb38cc2'/appId: 'LH8ZzpbwJuHH6xGFk6GgmtSC'/g" src/App.vue

    - name: Replace strings in package.json
      run: |
        sed -i 's/"build": "vite build --watch",/"build": "vite build",/g' package.json

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Replace strings" && echo "Pushing changes to the repository" && git push || echo "No changes to push"
